---
version: '3'
services:
  ceos-1:
    image: ${CEOS_VERSION}
    container_name: ceos-1
    command:
      - "/sbin/init"
    environment:
      container: docker
      EOS_PLATFORM: ceoslab
      CEOS: 1
      SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: 1
      ETBA: 1
      INTFTYPE: eth
    tty: true
    volumes:
      - ./configs/ceos-1:/mnt/flash
    privileged: true
    build: .
    networks:
      - management

  ceos-2:
    image: ${CEOS_VERSION}
    container_name: ceos-2
    command:
      - "/sbin/init"
    environment:
      container: docker
      CEOS: 1
      EOS_PLATFORM: ceoslab
      SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: 1
      ETBA: 1
      INTFTYPE: eth
    tty: true
    volumes:
      - ./configs/ceos-2:/mnt/flash
    privileged: true
    build: .
    networks:
      - management

  ubuntu-control:
    image: burnyd/ubuntu-oc
    container_name: mgt1
    command: tail -f /dev/null
    networks:
      - management

  oc-gobgp:
    image: burnyd/oc-gobgp:latest
    container_name: gobgp
    networks:
      - management

networks:
  management:
    driver: bridge

volumes:
  ceos-1:
  ceos-2:

